#---
#--- 0xproto
#---

font_family 0xProto
font_size 15.4
modify_font cell_height -5px
modify_font baseline 2
modify_font underline_thickness 40%
symbol_map U+4E00-U+9FFF,U+3400-U+4DBF,U+20000-U+2A6DF,U+2A700-U+2B73F,U+2B740-U+2B81F,U+2B820-U+2CEAF,U+F900-U+FAFF,U+2F800-U+2FA1F,U+3000-U+303F LXGW WenKai Mono
